version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app
    depends_on:
    - redis
    env_file:
      - .env.prod
    command: npm run prod
  redis:
    image: redis:alpine
