version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    depends_on:
    - redis
    env_file:
      - .env
    command: npm run start
  redis:
    image: redis:alpine
